# Generated by Django 2.0.7 on 2019-07-12 05:14

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_auto_20190712_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('requirements', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
